name: destini_app_flutter
description: This project is a part of London App Brewery's Flutter Learning Course. This is the 2nd challenge project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
